//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    
    public partial class paObtenerTodosLosEventosXIdUsuario_Result1
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdUsuarioCreador { get; set; }
        public int IdServicio { get; set; }
        public string Nombre { get; set; }
        public int TipoUnidadEvento { get; set; }
        public System.DateTime HorarioInicial { get; set; }
        public System.DateTime HoraFinal { get; set; }
        public string UsuarioCreacion { get; set; }
    }
}
